import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import Provider from "@/components/provider"
import { ThemeProvider } from "@/components/theme-provider"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Provider>{children}</Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
